[provider]
cluster = "devnet"
wallet = "~/.config/solana/deploy_keypair.json"

[programs.localnet]
clockwork_network_program = "F8dKseqmBoAkHx3c58Lmb9TgJv5qeTf3BbtZZSEzYvUa"
clockwork_thread_program = "CLoCKyJ6DXBJqqu2VWx9RLbgnwwR6BMHHuyasVmfMzBh"
clockwork_webhook_program = "E7p5KFo8kKCDm6BUnWtnVFkQSYh6ZA6xaGAuvpv8NXTa"

[programs.testnet]
clockwork_network_program = "F8dKseqmBoAkHx3c58Lmb9TgJv5qeTf3BbtZZSEzYvUa"
clockwork_thread_program = "CLoCKyJ6DXBJqqu2VWx9RLbgnwwR6BMHHuyasVmfMzBh"
clockwork_webhook_program = "E7p5KFo8kKCDm6BUnWtnVFkQSYh6ZA6xaGAuvpv8NXTa"

[programs.mainnet]
clockwork_network_program = "F8dKseqmBoAkHx3c58Lmb9TgJv5qeTf3BbtZZSEzYvUa"
clockwork_thread_program = "CLoCKyJ6DXBJqqu2VWx9RLbgnwwR6BMHHuyasVmfMzBh"
clockwork_webhook_program = "E7p5KFo8kKCDm6BUnWtnVFkQSYh6ZA6xaGAuvpv8NXTa"

[programs.devnet]
clockwork_network_program = "BqZbdEZRfadcD4vFmq6N1eSnxYQkDuuFkG3QkJ2c6Bmm"
clockwork_thread_program = "8npQifLwM8EW8T5b8jqGhMBCjn1U3rSjwkt5wmVSbppW"
clockwork_webhook_program = "9oZYsvtqURK1ZJb9PD8GTLKuMHfaq4wvwD9R7p7KhdRb"

["https://testnet.atlas.xyz?apikey=a60f3e0b285c14806f77ba6213e3a298287f"]
clockwork_network_program = "BqZbdEZRfadcD4vFmq6N1eSnxYQkDuuFkG3QkJ2c6Bmm"
clockwork_thread_program = "8npQifLwM8EW8T5b8jqGhMBCjn1U3rSjwkt5wmVSbppW"
clockwork_webhook_program = "9oZYsvtqURK1ZJb9PD8GTLKuMHfaq4wvwD9R7p7KhdRb"

[features]
resolution = false
seeds = false
skip-lint = false

[registry]
url = "https://anchor.projectserum.com"

[toolchain]